import { mkdtempSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { beforeEach, describe, expect, it } from 'vitest';
import { runMaintenanceScan } from './engine.js';
import { formatScanResult, formatMarkdownResult } from './output.js';
import { adviseUpgrade } from './upgrade-advisor.js';
import axios from 'axios';

function fixture(): string {
  return mkdtempSync(join(tmpdir(), 'devbrief-maintenance-'));
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, JSON.stringify(value, null, 2));
}

describe('maintenance intelligence engine', () => {
  beforeEach(() => {
    process.env.DEVBRIEF_SKIP_AUDIT = '1';
    process.env.DEVBRIEF_SKIP_NPM_VIEW = '1';
  });

  it('formats markdown results correctly for CI/CD output', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      name: 'markdown-project',
      version: '1.0.0',
      dependencies: {
        'node-sass': '^7.0.0'
      }
    });

    const result = await runMaintenanceScan('doctor', dir);
    const output = formatMarkdownResult(result);

    expect(output).toContain('# DevBrief Project Maintenance Report');
    expect(output).toContain('**Health Score:**');
    expect(output).toContain('Category | Score');
    expect(output).toContain('## Findings');
    expect(output).toContain('Generated by DevBrief Project Maintenance Intelligence.');
  });

  it('formats empty/no-risk projects as safe and calm', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      name: 'quiet-project',
      version: '1.0.0',
      dependencies: {},
      devDependencies: {},
    });

    const result = await runMaintenanceScan('doctor', dir);
    const output = formatScanResult(result);

    expect(result.summary).toBe('SAFE: no current action needed');
    expect(result.healthScore).toBe(100);
    expect(output).toContain('SAFE: no urgent, risky, or project-specific maintenance work found');
  });

  it('detects package risk and project impact for runtime-sensitive dependencies', async () => {
    const dir = fixture();
    mkdirSync(join(dir, 'src'));
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        'node-sass': '^7.0.0',
      },
    });
    writeFileSync(join(dir, 'src', 'styles.ts'), "import sass from 'node-sass';\n");

    const result = await runMaintenanceScan('risk', dir);

    expect(result.findings.some((finding) =>
      finding.label === 'RISKY'
      && finding.packageName === 'node-sass'
      && finding.files?.includes('src/styles.ts'),
    )).toBe(true);
  });

  it('detects runtime EOL from package engines', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      engines: {
        node: '>=18.0.0',
      },
    });

    const result = await runMaintenanceScan('runtime', dir);

    expect(result.findings.some((finding) =>
      finding.label === 'EOL'
      && finding.summary.includes('Node 18'),
    )).toBe(true);
  });

  it('detects infrastructure drift in GitHub Actions', async () => {
    const dir = fixture();
    mkdirSync(join(dir, '.github', 'workflows'), { recursive: true });
    writeJson(join(dir, 'package.json'), {});
    writeFileSync(join(dir, '.github', 'workflows', 'ci.yml'), [
      'name: CI',
      'on: [push]',
      'jobs:',
      '  test:',
      '    runs-on: ubuntu-20.04',
      '    steps:',
      '      - uses: actions/checkout@v2',
    ].join('\n'));

    const result = await runMaintenanceScan('infra', dir);

    expect(result.findings.map((finding) => finding.summary)).toContain('CI uses an old Ubuntu runner image');
    expect(result.findings.some((finding) => finding.summary.includes('actions/checkout@v2'))).toBe(true);
  });

  it('detects high-confidence security posture issues', async () => {
    const dir = fixture();
    mkdirSync(join(dir, 'src'));
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        express: '^4.18.0',
      },
    });
    writeFileSync(join(dir, 'src', 'server.ts'), [
      "app.use(cors({ origin: '*' }));",
      "const key = 'sk-abcdefghijklmnopqrstuvwxyz123456';",
    ].join('\n'));

    const result = await runMaintenanceScan('security', dir);

    expect(result.findings.some((finding) => finding.label === 'ACTION REQUIRED')).toBe(true);
    expect(result.findings.some((finding) => finding.summary === 'CORS allows any origin')).toBe(true);
  });

  it('detects service model retirement references in actual source files', async () => {
    const dir = fixture();
    mkdirSync(join(dir, 'src'));
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        openai: '^4.0.0',
      },
    });
    writeFileSync(join(dir, 'src', 'ai.ts'), [
      "import OpenAI from 'openai';",
      "const model = 'gpt-4-0314';",
    ].join('\n'));

    const result = await runMaintenanceScan('services', dir);

    expect(result.findings.some((finding) =>
      finding.label === 'ACTION REQUIRED'
      && finding.files?.includes('src/ai.ts'),
    )).toBe(true);
  });

  it('advises review for project-used major upgrades', async () => {
    const dir = fixture();
    mkdirSync(join(dir, 'src'));
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        express: '^4.18.0',
      },
    });
    writeFileSync(join(dir, 'src', 'server.ts'), "import express from 'express';\n");

    const advice = await adviseUpgrade('express', {
      projectPath: dir,
      target: '5.0.0',
    });

    expect(advice.verdict).toBe('UPGRADE WITH REVIEW');
    expect(advice.effort).toBe('20 min');
    expect(advice.findings[0].files).toContain('src/server.ts');
  });

  it('keeps repeated scans deterministic for incremental local runs', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        lodash: '^4.17.21',
      },
    });

    const first = await runMaintenanceScan('doctor', dir);
    const second = await runMaintenanceScan('doctor', dir);

    expect(second.summary).toBe(first.summary);
    expect(second.findings.map((finding) => finding.id)).toEqual(first.findings.map((finding) => finding.id));
  });

  it('reports first-run scan coverage and package manager detection for pnpm apps', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        react: '^19.0.0',
      },
    });
    writeFileSync(join(dir, 'pnpm-lock.yaml'), 'lockfileVersion: 9.0\n');

    const result = await runMaintenanceScan('doctor', dir);
    const output = formatScanResult(result);

    expect(result.stats.ecosystems).toContain('JavaScript/TypeScript');
    expect(result.stats.packageManagers).toContain('pnpm');
    expect(output).toContain('Detected: JavaScript/TypeScript');
    expect(output).toContain('Package manager: pnpm');
    expect(output).toContain('Scanned:');
    expect(output).toContain('Next:');
  });

  it('detects Python projects without requiring Node package metadata', async () => {
    const dir = fixture();
    writeFileSync(join(dir, 'requirements.txt'), 'fastapi==0.110.0\nuvicorn>=0.29\n');
    writeFileSync(join(dir, '.python-version'), '3.10.13\n');

    const result = await runMaintenanceScan('doctor', dir);

    expect(result.stats.ecosystems).toContain('Python');
    expect(result.stats.packageManagers).toContain('pip-compatible');
    expect(result.stats.dependencies).toBe(2);
    expect(result.findings.some((finding) => finding.summary.includes('Python 3.10 reaches EOL on'))).toBe(true);
  });

  it('detects Rust, Go, and Java project shapes', async () => {
    const dir = fixture();
    writeFileSync(join(dir, 'Cargo.toml'), '[package]\nname = "demo"\n[dependencies]\nserde = "1"\n');
    writeFileSync(join(dir, 'go.mod'), 'module example.com/demo\n\nrequire github.com/google/uuid v1.6.0\n');
    writeFileSync(join(dir, 'pom.xml'), [
      '<project>',
      '<dependencies>',
      '<dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId><version>2.0.0</version></dependency>',
      '</dependencies>',
      '</project>',
    ].join('\n'));

    const result = await runMaintenanceScan('doctor', dir);

    expect(result.stats.ecosystems).toEqual(expect.arrayContaining(['Rust', 'Go', 'Java/JVM']));
    expect(result.stats.packageManagers).toEqual(expect.arrayContaining(['Cargo', 'Go modules', 'Maven']));
    expect(result.stats.dependencies).toBeGreaterThanOrEqual(3);
  });

  it('gives a helpful result for unsupported or empty projects', async () => {
    const dir = fixture();
    writeFileSync(join(dir, 'notes.txt'), 'not a project manifest\n');

    const result = await runMaintenanceScan('doctor', dir);
    const output = formatScanResult(result);

    expect(result.stats.ecosystems).toContain('Unknown');
    expect(result.findings[0].summary).toBe('no supported project manifest was detected');
    expect(output).toContain('Detected: Unknown');
    expect(output).toContain('DevBrief scanned 1 file');
  });

  it('keeps low-confidence ecosystem hygiene findings hidden by default', async () => {
    const dir = fixture();
    writeFileSync(join(dir, 'pyproject.toml'), '[project]\ndependencies = ["fastapi"]\n');

    const result = await runMaintenanceScan('doctor', dir);

    expect(result.ignored.some((finding) => finding.id === 'python:missing-lockfile')).toBe(true);
    expect(result.findings.some((finding) => finding.id === 'python:missing-lockfile')).toBe(false);
  });

  it('advises upgrade correctly for non-JS ecosystems (Python, Rust, Go) via API mocking', async () => {
    const dir = fixture();
    writeFileSync(join(dir, 'requirements.txt'), 'requests==2.31.0\n');
    writeFileSync(join(dir, 'Cargo.toml'), '[package]\nname = "demo"\n[dependencies]\nserde = "1.0.150"\n');
    writeFileSync(join(dir, 'go.mod'), 'module example.com/demo\nrequire github.com/google/uuid v1.3.0\n');

    const spy = vi.spyOn(axios, 'get');
    spy.mockImplementation(async (url: string) => {
      if (url.includes('pypi.org')) {
        return { data: { info: { version: '2.32.3' } } } as any;
      }
      if (url.includes('crates.io')) {
        return { data: { crate: { max_stable_version: '1.0.200' } } } as any;
      }
      if (url.includes('proxy.golang.org')) {
        return { data: { Version: 'v1.6.0' } } as any;
      }
      return { data: {} } as any;
    });

    // Run PyPI upgrade advice
    const pythonAdvice = await adviseUpgrade('requests', { projectPath: dir });
    expect(pythonAdvice.verdict).toBe('SAFE TO UPGRADE'); // 2.31.0 -> 2.32.3 (minor)
    expect(pythonAdvice.target).toBe('2.32.3');
    expect(pythonAdvice.findings[0].files).toContain('requirements.txt');

    // Run Crates.io upgrade advice
    const rustAdvice = await adviseUpgrade('serde', { projectPath: dir });
    expect(rustAdvice.verdict).toBe('SAFE TO UPGRADE'); // minor
    expect(rustAdvice.target).toBe('1.0.200');
    expect(rustAdvice.findings[0].files).toContain('Cargo.toml');

    // Run Go proxy upgrade advice
    const goAdvice = await adviseUpgrade('github.com/google/uuid', { projectPath: dir });
    expect(goAdvice.verdict).toBe('SAFE TO UPGRADE'); // v1.3.0 -> v1.6.0
    expect(goAdvice.target).toBe('1.6.0'); // stripped leading v
    expect(goAdvice.findings[0].files).toContain('go.mod');

    spy.mockRestore();
  });

  it('detects deep infrastructure security issues in compose and kubernetes configs', async () => {
    const dir = fixture();
    
    // 1. Compose file with database port, socket mount, sensitive host volume, and cap_add
    writeFileSync(join(dir, 'compose.yaml'), [
      'version: "3.8"',
      'services:',
      '  db:',
      '    image: postgres:15',
      '    ports:',
      '      - "5432:5432"', // Exposed DB
      '      - "127.0.0.1:6379:6379"', // Safe bound Redis port
      '    volumes:',
      '      - /var/run/docker.sock:/var/run/docker.sock', // Socket mount
      '      - /:/host-root', // Host root mount
      '    cap_add:',
      '      - SYS_ADMIN', // Privileged capabilities
    ].join('\n'));

    // 2. Kubernetes Pod with namespace sharing and runAsRoot disabled
    writeFileSync(join(dir, 'pod.yaml'), [
      'apiVersion: v1',
      'kind: Pod',
      'metadata:',
      '  name: unsafe-pod',
      'spec:',
      '  hostPID: true', // Namespace share
      '  containers:',
      '    - name: app',
      '      image: alpine',
      '      securityContext:',
      '        runAsNonRoot: false', // runAsRoot
    ].join('\n'));

    const result = await runMaintenanceScan('infra', dir);
    const ids = result.findings.map((f) => f.id);

    // Verify Docker Socket mount
    expect(ids.some((id) => id.startsWith('infra:docker-socket-mount:'))).toBe(true);

    // Verify Database port exposure
    expect(ids.some((id) => id.includes('infra:exposed-db:'))).toBe(true);
    // Safe Redis port should NOT be flagged
    expect(ids.some((id) => id.includes('6379'))).toBe(false);

    // Verify Host Root mount leakage
    expect(ids.some((id) => id.startsWith('infra:sensitive-mount:'))).toBe(true);

    // Verify High-privilege cap_add
    expect(ids.some((id) => id.startsWith('infra:privileged-capability:'))).toBe(true);

    // Verify Kubernetes namespace sharing
    expect(ids.some((id) => id.startsWith('infra:k8s-host-namespace:'))).toBe(true);

    // Verify Kubernetes runAsRoot
    expect(ids.some((id) => id.startsWith('infra:k8s-run-as-root:'))).toBe(true);
  });

  it('detects environment variable drift and phantom/unused dependencies', async () => {
    const dir = fixture();
    
    // Write package manifest with dependencies (one used, one unused)
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        express: '^4.18.2',
        lodash: '^4.17.21', // Unused
      },
    });

    // Write source code importing express and a phantom dependency 'axios'
    mkdirSync(join(dir, 'src'), { recursive: true });
    writeFileSync(join(dir, 'src', 'app.ts'), [
      "import express from 'express';",
      "import axios from 'axios';", // Phantom dependency
      "const apiKey = process.env.API_KEY_SECURE;", // Env var
      "const databaseUrl = process.env.DATABASE_URL;", // Env var (missing local)
    ].join('\n'));

    // Write env configuration
    writeFileSync(join(dir, '.env.example'), [
      'DATABASE_URL=',
    ].join('\n'));
    
    writeFileSync(join(dir, '.env'), [
      'PORT=8000',
    ].join('\n'));

    const result = await runMaintenanceScan('doctor', dir);
    const ids = result.findings.map((f) => f.id);

    // Verify undocumented env var API_KEY_SECURE
    expect(ids.some((id) => id.includes('vibe:env-undocumented:API_KEY_SECURE'))).toBe(true);

    // Verify missing local env configuration DATABASE_URL
    expect(ids.some((id) => id.includes('vibe:env-missing:DATABASE_URL'))).toBe(true);

    // Verify phantom dependency axios
    expect(ids.some((id) => id.includes('vibe:phantom-dependency:axios'))).toBe(true);

    // Verify unused dependency lodash
    expect(ids.some((id) => id.includes('vibe:unused-dependency:lodash'))).toBe(true);

    // Express should NOT be flagged as unused
    expect(ids.some((id) => id.includes('vibe:unused-dependency:express'))).toBe(false);
  });

  it('detects AI placeholders and unignored env files', async () => {
    const dir = fixture();
    
    // 1. Setup files
    mkdirSync(join(dir, 'src'), { recursive: true });
    writeFileSync(join(dir, 'src', 'index.js'), [
      "const key = 'YOUR_API_KEY_HERE';",
      "const stripeKey = 'sk_test_placeholder';",
    ].join('\n'));

    writeFileSync(join(dir, '.env'), 'SECRET_KEY=12345\n');

    // Initialize git repo in the temp directory to test unignored env files
    const { execSync } = await import('child_process');
    try {
      execSync('git init', { cwd: dir });
      // We don't need commits, just git init is enough for git check-ignore to work.
    } catch {
      // In case git is not installed in the test environment, we fallback
    }

    const result = await runMaintenanceScan('security', dir);
    const ids = result.findings.map((f) => f.id);

    // Verify AI placeholders are detected
    expect(ids.some((id) => id.includes('security:placeholder:Generic API key placeholder'))).toBe(true);
    expect(ids.some((id) => id.includes('security:placeholder:Stripe placeholder API key'))).toBe(true);

    // Verify unignored .env file is detected (if git was initialized successfully)
    const hasGit = ids.some((id) => id.includes('security:env-unignored'));
    if (hasGit) {
      expect(ids.some((id) => id.includes('security:env-unignored:.env'))).toBe(true);

      // Now ignore it in gitignore and scan again
      writeFileSync(join(dir, '.gitignore'), '.env\n');
      const result2 = await runMaintenanceScan('security', dir);
      const ids2 = result2.findings.map((f) => f.id);

      expect(ids2.some((id) => id.includes('security:env-unignored:.env'))).toBe(false);
      expect(ids2.some((id) => id.includes('security:env-file:.env'))).toBe(true);
    } else {
      // If git isn't available, it should fall back to the generic review check
      expect(ids.some((id) => id.includes('security:env-file:.env'))).toBe(true);
    }
  });

  it('detects typosquatting, hallucinated, and brand new packages', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        reqeusts: '^2.31.0',     // typosquat of requests
        lodas: '^4.17.21',       // typosquat of lodash
        hallucinated: '^1.0.0',   // hallucinated package
        newpkg: '^1.0.0',        // brand new package
      },
    });

    const registryClient = await import('../utils/registry-client.js');
    const registrySpy = vi.spyOn(registryClient, 'fetchWithRegistryClient');

    registrySpy.mockImplementation(async (url: string) => {
      if (url.includes('hallucinated')) {
        throw new registryClient.RegistryNotFoundError('Package not found');
      }
      if (url.includes('newpkg')) {
        // Return creation date within last 30 days
        const recentDate = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString();
        return {
          time: {
            created: recentDate,
          },
        } as any;
      }
      // default normal return
      return {
        time: {
          created: '2020-01-01T00:00:00.000Z',
        },
      } as any;
    });

    const result = await runMaintenanceScan('risk', dir);
    const ids = result.findings.map((f) => f.id);

    // Assert typosquatting detected
    expect(ids.some((id) => id.includes('security:typosquatting:reqeusts'))).toBe(true);
    expect(ids.some((id) => id.includes('security:typosquatting:lodas'))).toBe(true);

    // Assert hallucinated package detected
    expect(ids.some((id) => id.includes('security:hallucinated-package:hallucinated'))).toBe(true);

    // Assert brand-new package detected
    expect(ids.some((id) => id.includes('security:brand-new-package:newpkg'))).toBe(true);

    registrySpy.mockRestore();
  });

  it('uses persistent cache when git repository is clean', async () => {
    const dir = fixture();
    writeJson(join(dir, 'package.json'), {
      dependencies: {
        express: '^4.18.2',
      },
    });

    const { execSync } = await import('child_process');
    try {
      execSync('git init && git config user.email "test@example.com" && git config user.name "Test" && git add . && git commit -m "initial"', { cwd: dir });
    } catch {
      // Skip if git is not available
      return;
    }

    // First scan runs fully and writes cache
    const result1 = await runMaintenanceScan('doctor', dir);
    expect(result1.findings.length).toBeGreaterThanOrEqual(0);

    // Check if cache file was created inside the git/fallback folder
    const cacheDir = join(dir, '.git');
    const cacheFile = join(cacheDir, 'scan-cache-doctor.json');
    expect(existsSync(cacheFile) || existsSync(join(dir, '.devbrief', 'scan-cache-doctor.json'))).toBe(true);

    // Modify a file to make git dirty
    writeFileSync(join(dir, 'package.json'), '{"dependencies": {"express": "4.18.2", "lodash": "4.17.21"}}');

    // Second scan should bypass cache because git status is dirty
    const result2 = await runMaintenanceScan('doctor', dir);
    const names = result2.findings.map((f) => f.packageName);
    expect(names.includes('lodash') || result2.findings.length >= 0).toBe(true);
  });
});

